# Generated by Django 5.0.6 on 2024-08-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kangacook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
