# Generated by Django 5.0.6 on 2024-08-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kangacook', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
