# Generated by Django 5.0.6 on 2024-08-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kangacook', '0006_remove_user_groups_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
