# Generated by Django 5.0.6 on 2024-08-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kangacook', '0009_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
