# Generated by Django 5.0.6 on 2024-08-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kangacook', '0011_remove_user_groups_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
